Update aws-eks-cluster.yml

diff --git a/.github/workflows/aws-eks-cluster.yml b/.github/workflows/aws-eks-cluster.yml
--- a/.github/workflows/aws-eks-cluster.yml
+++ b/.github/workflows/aws-eks-cluster.yml
@@ -36,4 +36,5 @@ jobs:
         terraform_version: 1.1.0
 
     - name: Terraform Init
-      run: terraform init
+      run: |
+        terraform init || { echo 'Error: Terraform init failed' ; exit 1; }
