Update aws-eks-cluster.yml

diff --git a/.github/workflows/aws-eks-cluster.yml b/.github/workflows/aws-eks-cluster.yml
--- a/.github/workflows/aws-eks-cluster.yml
+++ b/.github/workflows/aws-eks-cluster.yml
@@ -37,4 +37,9 @@ jobs:
 
     - name: Terraform Init
       run: |
-        /home/ubuntu/_work/_temp/799c7614-a3fa-469b-b418-a35a9202287b/terraform-bin init --ignore-preflight-errors=git || { echo 'Error: Terraform init failed' ; exit 1; }
+        if [ -f /home/ubuntu/_work/_temp/799c7614-a3fa-469b-b418-a35a9202287b/terraform-bin ]; then
+          /home/ubuntu/_work/_temp/799c7614-a3fa-469b-b418-a35a9202287b/terraform-bin init --ignore-preflight-errors=git || { echo 'Error: Terraform init failed' ; exit 1; }
+        else
+          echo 'Error: Terraform binary not found'
+          exit 1
+        fi
